newline_style = "Unix"
use_field_init_shorthand = true

unstable_features = true
style_edition = "2021"
imports_granularity = "Module"
group_imports = "StdExternalCrate"

format_code_in_doc_comments = true
format_macro_bodies = true
format_macro_matchers = true
