[package]
name = "compose-derive"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
darling = "0.13"
syn = { version = "1.0", features = ["full"] }
quote = "1.0"